# Generated by Django 4.0 on 2021-12-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='avatar')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('short_description', models.TextField(verbose_name='short_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
            },
        ),
    ]
